### ISSUE TITLE
Float128 somehow not supported with numpy on Windows machine. 

### ISSUE THREAD

**Issue by 1ozturkbe** [rileyjmurray/sageopt#1]
Hello Riley! I installed sageopt as instructed and ran the tests, which immediately errored out. 
```python
nosetests sageopt/tests
E
======================================================================
ERROR: Failure: AttributeError (module 'numpy' has no attribute 'float128')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\berk\appdata\local\programs\python\python37\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "c:\users\berk\appdata\local\programs\python\python37\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "c:\users\berk\appdata\local\programs\python\python37\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "c:\users\berk\appdata\local\programs\python\python37\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "c:\users\berk\appdata\local\programs\python\python37\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "c:\users\berk\appdata\local\programs\python\python37\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\sageopt\sageopt\__init__.py", line 16, in <module>
    from sageopt import coniclifts
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\sageopt\sageopt\coniclifts\__init__.py", line 1, in <module>
    from sageopt.coniclifts.base import Variable, ScalarVariable, Expression
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\sageopt\sageopt\coniclifts\base.py", line 20, in <module>
    from sageopt.coniclifts.utilities import array_index_iterator, __REAL_TYPES__
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\sageopt\sageopt\coniclifts\utilities.py", line 21, in <module>
    __REAL_TYPES__ = (int, float, np.int_, np.float_, np.float128)
AttributeError: module 'numpy' has no attribute 'float128'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
Apparently this [isn't a new problem.](https://github.com/winpython/winpython/issues/613) But unless it is absolutely necessary, it would make sense to try some other type. 
Also note [here](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.types.html), the following, quote: 'In spite of the names, np.float96 and np.float128 provide only as much precision as np.longdouble, that is, 80 bits on most x86 machines and 64 bits in standard Windows builds.'

**Comment by 1ozturkbe** [comment]
Btw, I have numpy 1.17.2.

**Comment by rileyjmurray** [comment]
Thanks for pointing this out Berk (and thanks especially for pointing out how numpy's ``float128`` doesn't do quite what I think it does). I will push a fix right away.

**Comment by rileyjmurray** [comment]
@1ozturkbe I have pushed a fix to the master branch. Can you install from source and verify that tests pass on your Windows box? I believe I removed all references to ``np.float128``, but I can't be sure without running it on Windows, and I don't have ready access to a Windows machine.

**Comment by 1ozturkbe** [comment]
Got 3 skips, but otherwise everything was fine.

**Comment by rileyjmurray** [comment]
Excellent! Those skips were just because sageopt didn't detect MOSEK in your python environment.

I will upload a new release to PyPI with this fix in a couple days. (I would upload the fix now, but there are some other small changes I'd like to package together with the next update.)

**Comment by 1ozturkbe** [comment]
Great. Also congrats on your first issue! ;)
